services:

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8180:8080"
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider http://localhost:8080/realms/test-realm 2>&1 | grep -v 'failed' || exit 0" ]
      interval: 15s
      timeout: 10s
      retries: 20
      start_period: 60s

  api-tests:
    build: .
    command: >
      test -Pkeycloak
      -DBASE_URL=https://dummyjson.com
      -DAUTH_URL=http://keycloak:8080/realms/test-realm/protocol/openid-connect/token
      -DAUTH_CLIENT_ID=api-test-client
      -DAUTH_CLIENT_SECRET=api-test-secret
      -DAUTH_GRANT_TYPE=client_credentials
    depends_on:
      keycloak:
        condition: service_healthy
    volumes:
      - ./target/allure-results:/app/target/allure-results