version: '3.8'

services:
  api-tests:
    build: .
    # Override CMD iz Dockerfile — integration profile
    command: >
      test -Pintegration
      -DBASE_URL=https://dummyjson.com
      -DAUTH_URL=https://dummyjson.com/auth/login
      -DAUTH_USERNAME=emilys
      -DAUTH_PASSWORD=emilyspass
    volumes:
      - ./target/allure-results:/app/target/allure-results