services:
  mock-service:
    image: wiremock/wiremock:latest
    ports:
      - "8080:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/__admin/mappings"]
      interval: 5s
      timeout: 3s
      retries: 5

  api-tests:
    build: .
    # Override CMD iz Dockerfile — mock profile
    command: >
      test -Pmock
      -DBASE_URL=http://mock-service:8080
      -DAUTH_URL=http://mock-service:8080/auth/login
      -DAUTH_USERNAME=emilys
      -DAUTH_PASSWORD=emilyspass
    depends_on:
      mock-service:
        condition: service_healthy
    volumes:
      - ./target/allure-results:/app/target/allure-results